# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jembe', '0002_auto_20170709_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 9, 14, 34, 4, 496003, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
