# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 12:41
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
